newyears_day:
    month: 1
    date: 1
    caption: 元旦
age_day:
    month: 1
    date: 12
    caption: 成人の日
foundation_day:
    month: 2
    date: 11
    caption: 建国記念日
spring_day:
    month: 3
    date: 21
    caption: 春分の日
syowa_day:
    month: 4
    date: 29
    caption: 昭和の日
constitution_day:
    month: 5
    date: 3
    caption: 憲法記念日
green_day:
    month: 5
    date: 4
    caption: みどりの日
children_day:
    month: 5
    date: 5
    caption: 子供の日
constitution_day_substitute:
    month: 5
    date: 6
    caption: 振替休日
marine_day:
    month: 7
    date: 20
    caption: 海の日
aged_day:
    month: 9
    date: 21
    caption: 敬老の日
national_holiday:
    month: 9
    date: 22
    caption: 国民の休日
autumn_day:
    month: 9
    date: 23
    caption: 秋分の日
sports_day:
    month: 10
    date: 12
    caption: 体育の日
culture_day:
    month: 11
    date: 3
    caption: 文化の日
thanks_giving_day:
    month: 11
    date: 23
    caption: 勤労感謝の日
emperors_birth_day:
    month: 12
    date: 23
    caption: 天皇誕生日
