'2019-01-01':
    caption: 元旦
    month: '1'
    date: '1'
'2019-01-14':
    caption: 成人の日
    month: '1'
    date: '14'
'2019-02-11':
    caption: 建国記念日
    month: '2'
    date: '11'
'2019-03-21':
    caption: 春分の日
    month: '3'
    date: '21'
'2019-04-29':
    caption: 昭和の日
    month: '4'
    date: '29'
'2019-04-30':
    caption: 国民の休日
    month: 4
    date: 30
'2019-05-01':
    caption: 天皇即位の日
    month: 5
    date: 1
'2019-05-02':
    caption: 国民の休日
    month: 5
    date: 2
'2019-05-03':
    caption: 憲法記念日
    month: '5'
    date: '3'
'2019-05-04':
    caption: みどりの日
    month: '5'
    date: '4'
'2019-05-05':
    caption: 子供の日
    month: '5'
    date: '5'
'2019-05-06':
    caption: 振替休日
    month: '5'
    date: '6'
'2019-07-15':
    caption: 海の日
    month: '7'
    date: '15'
'2019-08-11':
    caption: 山の日
    month: '8'
    date: '11'
'2019-08-12':
    caption: 振替休日
    month: '8'
    date: '12'
'2019-09-16':
    caption: 敬老の日
    month: '9'
    date: '16'
'2019-09-23':
    caption: 秋分の日
    month: '9'
    date: '23'
'2019-10-14':
    caption: 体育の日
    month: '10'
    date: '14'
'2019-10-22':
    caption: 即位礼正殿の儀の日
    month: 10
    date: 22
'2019-11-03':
    caption: 文化の日
    month: '11'
    date: '3'
'2019-11-04':
    caption: 振替休日
    month: '11'
    date: '4'
'2019-11-23':
    caption: 勤労感謝の日
    month: '11'
    date: '23'
