newyear_day: { type: fixed, month: 1, date: 1, caption: "元旦" }
age_day: { type: happymonday, month: 1, seq: 2, caption: "成人の日" }
foundation_day: { type: fixed, month: 2, date: 11, caption: "建国記念日" }
emperors_birth_day: { type: fixed, month: 2, date: 23, caption: "天皇誕生日" }
spring_day: { type: spring, month: 3, caption: "春分の日" }
syowa_day: { type: fixed, month: 4, date: 29, caption: "昭和の日" }
constitution_day: { type: fixed, month: 5, date: 3, caption: "憲法記念日" }
green_day: { type: fixed, month: 5, date: 4, caption: "みどりの日" }
children_day: { type: fixed, month: 5, date: 5, caption: "子供の日" }
marine_day: { type: happymonday, month: 7, seq: 3, caption: "海の日" }
mountain_day: { type: fixed, month: 8, date: 11, caption: "山の日" }
aged_day: { type: happymonday, month: 9, seq: 3, caption: "敬老の日" }
autumn_day: { type: autumn, month: 9, caption: "秋分の日" }
sports_day: { type: happymonday, month: 10, seq: 2, caption: "スポーツの日" }
culture_day: { type: fixed, month: 11, date: 3, caption: "文化の日" }
thanks_giving_day: { type: fixed, month: 11, date: 23, caption: "勤労感謝の日" }
